apiVersion: v1
kind: Pod

metadata:
  name: nginx
  labels: 
    software: reverse-proxy
    role: mypodpreset

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80


