apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: app1-env
spec:
  selector:
    matchLabels:
      role: mypodpreset
  env:
    - name: MY_JAVA_HOME
      value: "/usr/java/jdk.1.8.0_60"
