apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: app1-mounts
spec:
  selector:
    matchLabels:
      role: mypodpreset
  volumeMounts:
    - mountPath: /mydata
      name: web-volume
  volumes:
    - name: web-volume
      emptyDir: {}
