apiVersion: v1
kind: ResourceQuota

metadata:
    name: dev-resource-quota
    namespace: dev
spec:
    hard:
        requests.cpu: "0.5"
        requests.memory: 50Mi
        limits.cpu: "1"
        limits.memory: 1Gi

