apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    software: reverse-proxy       

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
