apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    software: reverse-proxy       

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
