apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-pod
  labels:
    app: initcontainer-app
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 60']
  initContainers:
  - name: initcontainer
    image: busybox
    command: ['sh', '-c', 'echo initcontainer start; sleep 10'] 
