apiVersion: v1
kind: Pod

metadata:
  name: nginx-multi-container
  labels:
    software: reverse-proxy

spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
      - containerPort: 80

  - name: tomcat-pod
    image: tomcat:8
    ports:
      - containerPort: 80


