apiVersion: v1
kind: Pod

metadata:
  name: nginxpod
  labels: 
    software: reverse-proxy

spec:
  containers:
  - name: mynginx
    image: nginx

  - name: tomcat
    image: tomcat:8

    ports:
      - containerPort: 8080

