kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: deployment-manager-binding
  namespace: devops
subjects:
- kind: User
  name: dave
  apiGroup: ""
roleRef:
  kind: Role
  name: dave-devops
  apiGroup: ""
