apiVersion: v1
kind: Pod

metadata:
  name: nginx
  labels: 
    software: reverse-proxy

spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
  
  nodeSelector:
    disktype: "ssd" 
    gpu: "true"

