apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: NodePort
  selector:
    software: frontend-webapp

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
    
