apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    - name: MAX_MEMORY
      valueFrom:
        configMapKeyRef:
          name: example-literal-config
          key: maxmemory

