apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    software: reverse-proxy
  template:
    metadata:
      name: nginx
      labels:
        software: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
