apiVersion: v1
kind: Pod

metadata:
  name: emptydir-pod
  labels:
    software: emptydir-reverse-proxy
spec:

  containers:
    - image: nginx
      name: emptydir-nginx

      volumeMounts:
      - mountPath: /cache
        name: cache-volume

  volumes:
    - name: cache-volume
      emptyDir: {}

    
