apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath-pod

spec:
  containers:
  - image: nginx
    name: nginx-hostpath
    volumeMounts:
      - mountPath: /nginx-hostpath
        name: hostpath-volume
  volumes:
  - name: hostpath-volume 
    hostPath:
        path: /data  
        type: DirectoryOrCreate 
