apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend2backend
  namespace: default
spec:
  podSelector:
    matchLabels:
      software: backend-api
      
  ingress:
  - from:
    - podSelector:
        matchLabels:
          software: frontend-webapp 
    ports:
    - protocol: TCP
      port: 5000
  policyTypes:
  - Ingress
