apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv2
  labels:
    type: local
spec:
  #storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 172.42.42.250
    path: "/var/nfsshare/"

